### ISSUE TITLE
Реализовать функцию "Создание цели с задачами"

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#1]
### Схема создания цели:

![Image](https://user-images.githubusercontent.com/107300467/229380013-b2bfe70c-e6b7-42d5-88c6-c110ee98812f.png)

### Обозначения:
Красные элементы - кнопки действий
Фиолетовые элементы - поля ввода данных от пользователя
Зелёные элементы - элементы отображения информации

Кнопка "+" - кнопка создания цели

Страница №1 - главная страница
Страница №2 - страница создания цели

Стрелками обозначен переход между страницами. Начало стрелки обозначает кнопку, которая запускает переход, конец стрелки обозначает страницу на которую происходит переход.

### Описание функции:
Пользователь с главной страницы нажимает на кнопку "+" и переходит на страницу создания цели. 
На этой странице находятся 2 поля ввода. 
В первом поле написано "Введите цель", во втором поле написано "Новая задача"
Пользователь вводит свою цель в первом поле
Пользователь вводит свою задачу во втором поле
Второе поле сдвигается вниз, а над ним появляется введённая задача
С каждым вводом новой задачи второе поле сдвигается вниз, формируя над собой список задач.
Пользователь нажимает кнопку "Сохранить" и переходит на главную страницу
На главной странице появляется созданная цель
Если пользователь создаст ещё одну цель, то она воявится ниже первой цели

**Comment by AlexValue** [comment]
Изменение в ТЗ:
На странице №2 отображается не поле для ввода задачи, а кнопка. При нажатии на эту кнопку появляется поле для введения задачи.

Изменение предложено Waranim, одобрено тимлидом.

**Comment by Waranim** [comment]
Goally1.1
https://bit.ly/43yejko
