### ISSUE TITLE
Изменить текст верхних вкладок на макете главной страницы

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#10]
Нужно заменить 2 надписи на верхнем переключателе вкладок:
"Все" заменить на "Цели"
"Завершено" заменить на "Архив"

![Image](https://user-images.githubusercontent.com/107300467/232024398-d62f455a-8a1e-43bd-9863-8cbcb10d8325.png)

В результате нужно прикрепить картинку в разрешении 1080 х 2340 с обновлённым макетом главной страницы.

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/232076072-32f68d17-5ad8-480a-917a-951b2254dc54.jpg)
