### ISSUE TITLE
Посмотреть лекцию по основам работы в Figma и созданию анимаций

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#11]
Посмотреть лекцию по ссылке
https://urfume.sharepoint.com/sites/msteams_c7e9e0/_layouts/15/stream.aspx?id=%2Fsites%2Fmsteams%5Fc7e9e0%2FShared%20Documents%2FGeneral%2FRecordings%2F%D0%9C%D0%B0%D1%81%D1%82%D0%B5%D1%80%2D%D0%BA%D0%BB%D0%B0%D1%81%D1%81%20%D0%BF%D0%BE%20Figma%2D20230412%5F174336%2D%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C%20%D1%81%D0%BE%D0%B1%D1%80%D0%B0%D0%BD%D0%B8%D1%8F%2Emp4

В результате, нужно написать в комментариях к этой карточке "Задание выполнено" после того, как лекция будет просмотрена

**Comment by AniaKoriakina** [comment]
Задание выполнено
