### ISSUE TITLE
Подготовить вопросы для последующего проведения опроса у целевой аудитории

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#13]
На следующем спринте мы проведём электронный опрос целевой аудитории (студентов) для аналитики.
Сейчас нужно продумать список вопросов, которые помогут собрать полезную информацию для разработки продукта.

Задачи:
1. Определить какая информация от целевой аудитории поможет нам в разработке продукта
2. Сформулировать список вопросов, которые помогут собрать эту информацию через опрос.
3. Составить предварительный вариант опроса в гугл формах (сам опрос пока не рассылаем!!!)

Очень важно тщательно поработать над первым пунктом, чтобы понять что нам нужно получить от целевой аудитории для разработки качественного продукта.

В гугл форме желательно использовать вопросы с разными формами ответа: выбор варианта, свободный текстовый ответ, шкала и другие возможности гугл форм.

В результате нужно прикрепить ссылку на форму в комментариях под этим заданием.

**Comment by Danashi11** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSde-G91DYcudFSC7xM33GAn3NTTdb30YYROgbzcff4FAHDl-w/viewform?usp=sharing
