### ISSUE TITLE
Распространить наш опрос среди аудитории всех возрастов

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#14]
Нужно распространить опрос среди максимально широкой аудитории, чтобы выявить целевую аудиторию и собрать о ней информацию. Желательно, чтобы опрос охватывал аудиторию всех возрастов, а не только студентов.

Ссылка для распространения:
https://forms.gle/S4syvzkmgDZmUBNY9

Цель - опросить не менее 25 человек
После достижения нужного количества ответов, нужно написать "Задание выполнено" в комментариях к этой картчоке

Внимание! Качество ответов приоритетнее количества. Лучше получить недобор, чем испорченную статистику.

Каких ситуаций нужно избегать при распространении опроса:
- Один человек голосует с нескольких аккаунтов
- Люди проходят опрос за несколько секунд не читая вопросы
- Люди голосуют "как надо", а не как они считают

**Comment by Danashi11** [comment]
Задание выполнено
