### ISSUE TITLE
Создать макет страницы "Просмотр информации о цели"

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#15]
**Описание страницы**
Эта страница будет вызываться, когда пользователь кликает на какую-либо созданную цель на главной странице.
На ней будет отображаться вся информация о цели
Также на этой странице можно будет выполнить подзадачу, создать новую подзадачу, удалить цель, заполнить пустые поля

**Информация, которая должна отображаться на этой странице**
1) Картинка цели
2) Текст цели
3) Описание цели
4) Дедлайн
5) Приоритет (присвоить значение "Срочно")
6) Категория (присвоить значение "Учёба")
7) Список целей

Нужно будет создать 2 варианта макета. 
У первого варианта будет только формулировка цели, остальные поля пучтые
У второго варианта будут заполнены все поля

**Кнопки действий, которые должны быть на странице**
1) Кнопка "<" для выхода со страницы
2) Кнопка для удаления цели
3) Кнопка для выполнения задачи (напротив каждой задачи). Обычно её рисуют как кружок
4) Кнопка для создания новой задачи

**Что должно быть в результате**
В результате, нужно прикрепить в комментариях к этой карточке 2 картинки макетов с разрешением 1080 х 2340
У первого варианта будет только формулировка цели, остальные поля пучтые
У второго варианта будут заполнены все поля

Внимание! Если все данные полей не влезут в макет, то можно показать эффект прокрутки страницы. Это означает, что одна картинка заменяется на 2, где на первой показана заполненая страница, где последний элемент заходит за край, а на второй картинке показано продолжение (элементы, которые не влезли)

**Comment by AniaKoriakina** [comment]
Первый вариант макета с пустыми полями. В верхний правый угол добавила элемент включения и выключения нотификашек

![Image](https://user-images.githubusercontent.com/82394052/234575611-030aa659-8cdb-4f21-8748-83f5fe5be933.jpg)

**Comment by AniaKoriakina** [comment]
Второй вариант макета с заполненными полями



![Image](https://user-images.githubusercontent.com/82394052/234579382-2b8b74f6-49c5-4584-96ce-a0e31b90275f.jpg)
![Image](https://user-images.githubusercontent.com/82394052/234579381-af8056d4-00f5-46c7-bf05-4c1cb971bec2.jpg)

**Comment by AlexValue** [comment]
В целом хорошо, но у меня есть несколько замечаний:

1) В задании было сказано, что должна быть кнопка удаления **цели**, а не каждой **задачи**. 
Эту кнопку можно разместить в правом верхнем углу, где сейчас находится переключатель уведомлений.
Напротив задач кнопку удаления можно пока убрать.

![Image](https://user-images.githubusercontent.com/107300467/234594895-e59acb2a-4e47-4f73-a98f-d25915dd72e2.png)


2) Из иконки удаления (мусорной корзины) стоит убрать 2 белые полоски внутри, потому что тонкие и мелкие элементы делают интерфейс менее современным и более сложным

![Image](https://user-images.githubusercontent.com/107300467/234594940-9520d7d5-9d2b-467f-9054-052d9e4d1149.png)

3) Переключатель уведомлений не интуитивно понятный элемент. Как пользователь узнает, что этот переключатель управляет уведомлениями а не чем-то другим?
Предлагаю заменить его иконкой колокольчика. По нажатию на неё будет открываться отдельная страница с настройкой уведомлений, поэтому достаточно нарисовать одну иконку без вариантов "включено", "выключено".
Колокольчик можно разместить левее кнопки "удалить цель" (см пункт №1 в замечаниях)

4) Интерфейс выглядит разрозненно и слишком сложно из-за того, что боксы задач в списке уже и короче, чем остальные боксы.
Предлагаю Разместить все задачи и кнопку создания задач в едином большом боксе.

5) Кнопка добавления задач должна быть в самом низу списка задач, чтобы пользователь мог видеть только что добавленные задачи (они будут появляться внизу списка, над кнопкой создания задачи)

6) Иконка галочки у выполненной задачи слишком тонкая и не вписывается в современный дизайн.
Предлагаю сделать её объёмной и квадратной (как в логотипе)

7) Цвета выполненной задачи не очень приятны моему глазу. 
Предлагаю поэксперементировать с разными оттенками, яркостью и насыщеностью зелёного цвета.
Можно подготовить несколько вариантов с разными оттенками и отправить мне в телеграме. Я скажу какой лучше.

8) В начальном положении страницы не понятно, что есть возможность прокрутить вниз.
Предлагаю добавить справа бегунок прокрутки страницы.

**Comment by AniaKoriakina** [comment]
Первый вариант макета с пустыми полями.
![Image](https://user-images.githubusercontent.com/82394052/235159431-d35686de-07c4-4848-bf0c-7b45e2ff8d8d.jpg)

**Comment by AniaKoriakina** [comment]
Второй вариант макета



![Image](https://user-images.githubusercontent.com/82394052/235085529-93261f82-a71c-45b2-8bb4-069cd3170b33.jpg)



![Image](https://user-images.githubusercontent.com/82394052/235085541-6a011d40-f8f2-4a7d-9a3c-aafb02549631.jpg)

**Comment by AlexValue** [comment]
1) Кнопку мусорной корзины стоит сделать более умеренного оттенка красного.
2) Колокольчик стоит сделать в стиле "flat icon" (заполненный) чтобы он был такого же стиля как мусорная корзина
3) Вверху бокса с задачами (либо за его пределами либо внутри, на твой вкус) нужно добавить надпись "Задачи", чтобы было понятно что это за список

Дополнительное требование:
Нужно добавить иконку календаря слева от колокольчика. Она также должна быть в стиле "flat icon"

В остальном, всё хорошо

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/235115804-410be331-1251-457c-93fb-1f4385855033.jpg)

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/235115871-f96a9276-5544-4730-9d0a-5616a3199bcb.jpg)



![Image](https://user-images.githubusercontent.com/82394052/235115882-4aae486a-3ff7-4b72-94cd-593fbe7e89e0.jpg)

**Comment by AlexValue** [comment]
1) Иконки календаря и колокольчика стоит сделать более светлого оттенка, они слишком выделяются
2) Надпись "задачи" над боксом находится слишком близко к краю бокса
3) Иконка календаря меньше иконки колокольика и мусорной корзины. Её стоит немного увеличить.
4) Иконка календаря плохо ассоциируется с календарём. её стоит либо изменить либо заменить на другую иконку календаря

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/235285368-e780ffc9-064a-42ee-8a2a-9492ef3f50b5.jpg)

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/235285377-85a0ee6b-d6bb-4d14-a7c8-ae0b49d7e537.jpg)
![Image](https://user-images.githubusercontent.com/82394052/235285378-3c552aea-99a9-4759-8642-7d12c2053594.jpg)

**Comment by AlexValue** [comment]
Предлагаю выровнять надпись "задачи" по центру, а не по левому краю

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/235310225-9918997c-4196-4748-9adc-9b087a3a6594.jpg)



![Image](https://user-images.githubusercontent.com/82394052/235310226-b96b34cb-2427-4bdd-a186-20d4ae97cef2.jpg)



![Image](https://user-images.githubusercontent.com/82394052/235310227-f38ce749-c1e3-4c26-8b47-bf385d49231b.jpg)
