### ISSUE TITLE
Добавить верхнюю и нижнюю панели во все макеты

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#16]
**Описание проблемы**
При отображении интерфейса на реальном устройстве, часть экрана занята 
верхней панелью, которая отображает время, уведомления и системные значки
и нижней панелью, которая отображает системную кнопку управления

Эти элементы меняют пропорции всего интерфейса, поэтому их нужно учесть на макете.

**Задание**
Сохранив общий размер и пропорции макета (1080 х 2340) нужно добавить в него нижнюю и вернюю панели.

**Пример как должно быть**

![Image](https://user-images.githubusercontent.com/107300467/234056247-d8486cc9-48d7-46d2-a762-20cd728045c0.png)

**Картинка, на которой обе панели выделены фиолетовым и чёрными цветами. По ней можно определить размеры панелей**

![Image](https://user-images.githubusercontent.com/107300467/234056586-8f8b6e07-08c9-432f-a911-b617fa61efda.png)

**Что должно быть в результате**
В результате нужно прикрепить изменённые варианты (с панелями) всех существующих макетов.
Эти панели также нужно будет включать во все будущие макеты.

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/234109379-cd65723b-817a-4408-9f8f-5c8a43c7a1e7.jpg)



![Image](https://user-images.githubusercontent.com/82394052/234109387-4c70385e-2d76-4b05-b204-87931f2d2cb9.jpg)
