### ISSUE TITLE
Выписать характеристики элементов, которые используются в макетах

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#17]
Нужно описать все характеристики элементов (код цвета, шрифт, размер шрифта, радиус скругления) на созданных макетах 
Код цвета должен быть в формате HEX

Эти характеристики будут нужны программисту для вёрстки. 

Вот как это можно оформить:
В цетре картинки макет интерфейса за его пределами все характеристики элементов
От этих характеристик идут стрелочки к элементам макета

Дизайнер может оформить это по другому, главное чтобы было понятно какая характеристика к какому элементу относится.

В результате нужно прикрепить картинку (или несколько картинок), на которых показаны характеристики элементов для существующих макетов.

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/234957869-30c5fa15-8d30-4415-baae-e9806daf42da.png)

**Comment by AlexValue** [comment]
Хорошо
К схеме главной страницы у меня только одно изменение:
Нужно описать ещё характеристики надписи "Goally"

![Image](https://user-images.githubusercontent.com/107300467/235066123-fc286f72-808d-46e6-a0b1-9fa783b8609f.png)

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/235116930-012e3092-ef1b-4e4d-a395-a712e84badf0.png)

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/235181235-88e8fa8d-7e2c-4521-8320-a62788a7b55b.png)

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/235796558-b3a82ce6-db93-47eb-9e0d-b0036dc93a4c.png)
