### ISSUE TITLE
Сделать прозрачными верхнюю и нижнюю панели

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#21]
Нужно сделать прозрачными верхнюю панель, где отображается время и уведомления (сейчас она фиолетовая)
и нижнюю панель, где отображаются системные кнопки управления (сейчас она чёрная)

В результате должно казаться, что эти 2 панели имеют такой же цвет, что и фон страницы. При этом весь текст и кнопки на этих панелях должен быть читабельны.

То что есть сейчас:

![Image](https://user-images.githubusercontent.com/107300467/234047435-74e31449-4809-4237-bcaf-a1108d5ddbb1.png)

Пример приложения с прозрачными панелями (как должно быть):

![Image](https://user-images.githubusercontent.com/107300467/234047877-dbaf120b-5426-4a14-a44f-4b2a8139e7ca.png)

В результате выполнения задания нужно произвести коммит кода для того, чтобы синхронизировать изменения c репозиторием.
Также нужно прикрепить в комментариях под этой карточкой ZIP архив с APK файлом изменённой программы для того, чтобы можно было протестировать её.

**Comment by Waranim** [comment]
[Goally1.3.3.zip](https://github.com/AlexValue/Goally/files/11334582/Goally1.3.3.zip)
