### ISSUE TITLE
Сформировать список используемых технологий

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#22]
Нужно сформировать список технологий, которые мы используем в продукте.

У нас уже есть общий список:
Kotlin – язык разработки мобильных приложений
Android Studio — среда разработки мобильных приложений
GitHub — сервис совместной работы
Telegram — мессенджер

Нужно дополнить его более конкретными пунктами.
Например, Rooms - библиотека для управления базой данных и др.

В результате нужно выписать список технологий в комментариях к этой карточке.

**Comment by Waranim** [comment]
SQLite - база данных
Rooms - библиотека для управления базой данных
