### ISSUE TITLE
Сформировать итоговый список конкурентов

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#23]
У нас уже есть короткий список конкурентов, который находится в документе с концептом. В результате опроса мы получили ещё несколько названий конкурентов.

Задача:
Опираясь на концепт и резульатыт опросы, составить небольшой доклад о конкурентах. Его чтение не должно занимать больше минуты. Этот доклад мы включим в наше выступление на предзащите.

В результате нужно написать в комментариях текст этого доклада.

**Comment by Danashi11** [comment]
Проведя опрос и проанализировав существующие продукты, мы выявили самые востребованные сервисы, которые являются нашими конкурентами. А именно: TickTick, Streaks, Way of Life, [Coach.me](https://coach.me/), Strides, Notion, Trello, google keep и обычные заметки. Мы стараемся создать наше приложение на основе лучшего , что есть в этих сервисах - установка сроков, распределение целей по категориям, настройка напоминаний, приятный дизайн и т.д. Соответственно отсеяли функции, которые только мешают пользователю - отсутствие перевода на русский язык, сложный интерфейс, невозможность отслеживать прогресс по отдельным целям, невозможность ставить подзадачи в бесплатной версии, навязчивая реклама в бесплатной версии.
