### ISSUE TITLE
Подготовить вариант в тёмной теме для всех трёх макетов

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#24]
Нужно подготовить варианты макетов в тёмной теме
На текущий момент у нас есть следующие макет: "Гланая страница", "Создание цели", "Просмотр информации о цели"

Также нужно подготовить схемы для этих 3 вариантов. Чтобы облегчить задание, на схемах нужно указывать только новые элементы, которые не были описаны в прошлых заданиях или схемах. В данном случае нужно описать только новые цвета.

В результате нужно прикрепить 3 картинки тёмных вариантов макетов и от 1 до 3 схем (в зависимости от количества макетов с уникальными элементами)

Разрешение картинок 1080 х 2340

**Comment by AniaKoriakina** [comment]
Схемы сделаю после подтверждения этих трёх макетов

![Image](https://user-images.githubusercontent.com/82394052/235304087-c266eb3c-5b86-4dcc-8002-b1608abf91b6.jpg)



![Image](https://user-images.githubusercontent.com/82394052/235304090-dd10cc1a-1cc3-452c-ba60-d1b82cd3ab38.jpg)



![Image](https://user-images.githubusercontent.com/82394052/235304094-e3a9f3bd-91b5-4048-8a64-41f10ab8fc5e.jpg)

**Comment by AlexValue** [comment]
1) У надписей, которые были чёрными появился фиолетовый оттенок, но у серых надписей и иконок этого оттенка не появилось. Нужно добавить оттенок в серые надписи и иконки.

![Image](https://user-images.githubusercontent.com/107300467/235305865-141e3dd9-b53c-4c4f-b661-162db77bb167.png)

![Image](https://user-images.githubusercontent.com/107300467/235305891-3c0cf4ce-0e6f-412e-8b00-56fac6aed90b.png)

![Image](https://user-images.githubusercontent.com/107300467/235306303-dfd998c8-9302-4615-8e41-0fec3e80046c.png)

![Image](https://user-images.githubusercontent.com/107300467/235306323-734f9a80-0bea-427e-a3d7-543dfe165d40.png)

![Image](https://user-images.githubusercontent.com/107300467/235306331-7c1c29be-7140-400c-b28d-18d32d5ff6cf.png)


2) Правая (пустая) часть строки прогресса должна быть тёмной. Можно залить её цветом фона страницы

![Image](https://user-images.githubusercontent.com/107300467/235305948-a237e70f-f254-429e-b17a-fed5c53a8c8e.png)

3) Кнопка "Отмена" не должна быть такого же цвета, как и поля. Она должна выделяться.

![Image](https://user-images.githubusercontent.com/107300467/235306050-6629a87e-5eec-4164-adfc-9e1dd69ac9f7.png)

4) Все элементы на оранжевых фонах должны сохранить белый цвет, как в светлой теме. Это повышеает их читаемость.

![Image](https://user-images.githubusercontent.com/107300467/235306117-42562ab0-c88e-4797-8869-dab2b4707969.png)

![Image](https://user-images.githubusercontent.com/107300467/235306129-bb798c2f-c8bd-42da-add5-c701b419c21d.png)

![Image](https://user-images.githubusercontent.com/107300467/235306153-41d333fe-7ddd-4a54-bf04-837ad7383fd5.png)

5) Оттенок мусорной корзины слишком выделяется в тёмной теме. Стоит поэксперементироваться с этим. Можно попробовать сделать его темнее и/или насыщенее

![Image](https://user-images.githubusercontent.com/107300467/235306362-bf9fdf04-5c31-4e7b-8e6f-a003ff4c1bed.png)

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/235310010-49e29fda-03e0-4126-b77d-b37e2bc6f3ea.jpg)
![Image](https://user-images.githubusercontent.com/82394052/235310011-41f386c0-888b-44e2-b1a0-0d3dae9ba22b.jpg)

![Image](https://user-images.githubusercontent.com/82394052/235310116-d2bb2e6c-3ef3-45d6-9e53-51bf99e8d77c.jpg)

**Comment by AlexValue** [comment]
1) Кнопка "Отмена" не гармонично выглядит по цвету с остальным интерфейсом. Она чисто серая, а интерфейс с оттенком другого цвета. Стоит, наоборот, усилить цвет кнопки из первого варианта, а не ослабить его.

2) Кнопка мусорной корзины слишком тёмная. Стоит сделать что-то среднее между первым и вторым вариантами


![Image](https://user-images.githubusercontent.com/107300467/235311619-a5458cc6-a203-43fb-a01a-d9828a2e3432.png)

![Image](https://user-images.githubusercontent.com/107300467/235311625-0dd1112d-15be-4e4a-bbba-ab5272b58f69.png)

3) Стоит сделать иконки нижнего меню менее светлыми

![Image](https://user-images.githubusercontent.com/107300467/235311746-39b68662-d87f-44df-97af-a9a2c949a82d.png)

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/235321101-5a3981d5-2f6c-4c5b-9439-c9d2c5b22c8c.jpg)
![Image](https://user-images.githubusercontent.com/82394052/235321102-630685bf-3c21-46e4-87de-ce0f5dbc06f6.jpg)
![Image](https://user-images.githubusercontent.com/82394052/235321103-2be04f97-40ae-46a6-8f18-37933afb5802.jpg)

**Comment by AlexValue** [comment]
1) Предлагаю использовать для иконки корзины цвет EB5666 (формат Hex)
Он немного менее насыщен и немного темнее самого первого варианта

2) Для кнопок нижнего меню предлагаю использовать цвет 644C86
![image](https://user-images.githubusercontent.com/107300467/235350112-6baf8f5c-3250-4604-9e4d-fb5c2de17702.png)


В остальном всё хорошо
Осталось сделать схему макетов в тёмной теме.

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/235350376-0d7bc721-c063-48a5-b814-7acaf2588ae5.jpg)



![Image](https://user-images.githubusercontent.com/82394052/235350378-2cb7b8d5-f6bd-41f4-94d1-e775620c8cdf.jpg)



![Image](https://user-images.githubusercontent.com/82394052/235350379-9b07b470-fae2-4f7b-bd71-6d069b3a2dc9.jpg)

**Comment by AniaKoriakina** [comment]
Макеты



![Image](https://user-images.githubusercontent.com/82394052/235516413-dee58c9e-5497-4a7d-807b-8da1980a1e8d.png)





![Image](https://user-images.githubusercontent.com/82394052/235516226-b49fb0f5-357f-4929-a3e6-a256148f7b3b.png)



![Image](https://user-images.githubusercontent.com/82394052/235516230-d62416e5-d4a9-43b0-a1d8-922d65f4cda6.png)
