### ISSUE TITLE
Реализовать функцию "Просмотр задач"

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#3]
### Схема просмотра задач

![Image](https://user-images.githubusercontent.com/107300467/229381728-ac121f0d-4f7d-4ec4-9d72-cfbbd6f93549.png)

### Обозначения:
Красные элементы - кнопки действий
Фиолетовые элементы - поля ввода данных от пользователя
Зелёные элементы - элементы отображения информации

Кнопка "<" - кнопка возврата на главную страницу

Страница №1 - главная страница
Страница №3 - страница с информацией о выбранной цели

Стрелками обозначен переход между страницами. Начало стрелки обозначает кнопку, которая запускает переход, конец стрелки обозначает страницу на которую происходит переход.

### Описание функции

- Пользователь нажимает на одну из целей на главной странице и переходит на страницу №3.
- На странице №3 отображается цель и задачи списком, в левом верхнем углу страницы №3 отображается кнопка "<"
- Пользователь нажимает на кнопку "<" и возвращается на главную страницу

**Comment by Waranim** [comment]
[Goally1.2.zip](https://github.com/AlexValue/Goally/files/11247647/Goally1.2.zip)

**Comment by AlexValue** [comment]
В целом всё хорошо. Но в тёмной теме отсутствует список задач на странице с информацией о цели. Поддержка тёмной темы указана в основных требованиях к приложению (см документ "Техническое задание"), поэтому такие требования не пишутся в карточке задания. Они применяются ко всем заданиям по умолчанию.

Задание выполнено не до конца. Возвращаю на доработку в колонку "Назначено"

**Comment by Waranim** [comment]
[Goally1.3.zip](https://github.com/AlexValue/Goally/files/11250880/Goally1.3.zip)

**Comment by AlexValue** [comment]
Принято
