### ISSUE TITLE
Создать макет интерфейса главной страницы

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#4]
### Описание страницы "Главная"
Это домашняя страница, куда пользователь попадает при запуске приложения.
Цель страницы - отображать главную информацию по целям

### Что должен показывать прототип:
1. UX - Расположение элементов с целью удобного использования всех функций пользователем
2. UI - Визуальное вополощение элементов с целю повышения эстетической привлекательности страницы

### Какие инструменты можно использовать для создания прототипа
Любой растровый редактор, например, Adobe XD
Любой векторный редактор, например, Figma
Среду разработки Android Studio

### На что ориентироваться:
1. Общие требования к проекту (см. документ "техническое задание" в чате)
2. Личная папка с референсами
3. Приложения конкурентов: "UP", "TickTick", "Цели и достижения"

### Какие элементы должны быть на прототипе страницы
1. Список целей пользователя
2. Картинка к конкретной цели цели
3. Количество выполненных задач к конкретной цели ("2 из 4", "9 из 10" и т.д.)
4. Отображение прогресса в виде строки у конкретной цели (заполнение строки зависит от количества выполненных задач у этой цели)
5. Дедлайн конкретной цели в формате дата и время "6 апр., 16:00"
6. Кнопка создания новой цели
7. Нижняя панель с 4 кнопками для переключения между страницами приложения. Эти кнопки будут вести на следующие страницы: "Главная", "Календарь", "Награды", "Остальное"

Пункты 2, 3, 4, 5 должны быть не у всех целей, изображённых на прототипе. Некоторые цели будут без этих данных, только с названием

### Что должно быть в результате
Макет страницы "Главная" в виде картинки
Соотношение сторон картинки должно быть 1080 х 2340

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/229793136-20897b67-b24f-41c6-a84e-3aa7e26a8b8e.png)

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/230343061-946e3816-6f07-4b88-b5f7-8e12f145a771.png)

**Comment by AlexValue** [comment]
Хороший результат
Но у меня есть 4 замечания к работе:

1) Измени, пожалуйста, цвет теста, который находится на оранжевой кнопке с чёрного на белый, чтобы он лучше читался

![Image](https://user-images.githubusercontent.com/107300467/230346762-16c39227-f622-4de7-8eae-549a5c584f14.png)

2) Сделай оттенок кнопки "+" чуть темнее, чтобы он совпадал по сцвету с остальными оранжевыми элементами.

![Image](https://user-images.githubusercontent.com/107300467/230347142-fa58e0ce-675b-476d-8991-1e3184b54ec3.png)

3) Сделай форму кнопки "+" в стиле Material You (квадрат со скруглёнными краями). Пример прикрепил ниже

![Image](https://user-images.githubusercontent.com/107300467/230347442-2629b69b-2599-488a-83d9-354daf8692e0.png)

4) Постарайся уменьшить количество деталей в иконках, чтобы сделать их современнее. Можно воспользоваться поиском по открытым базам иконок, например FlatIcon. Также картинки должны состоять только из одного цвета. Ориентироваться можно на стиль иконок "Line" как в приложении "UP" или в стиле "Flat" как в приложении "TickTick". 

![Image](https://user-images.githubusercontent.com/107300467/230349456-19f37854-6cf0-4db0-bfef-78ea20ef7cbc.png)

![Image](https://user-images.githubusercontent.com/107300467/230349530-4e265eec-de3d-459b-ba0d-ba020965c1c7.png)

5) Замени картинку аккаунта на иконку кнопки в правом верхнем углу. У нас в приложении не будет аккаунтов. Можно использовать иконку "три полоски", которую обычно используют для обозначания дополнительных параметров.

![Image](https://user-images.githubusercontent.com/107300467/230350037-d23d1111-beec-4c8e-88e8-2fad7cb0273c.png)

6) Цвет названия приложения в левом верхнем углу следует сделать однотонным, без градиентов. Это сделает его более современным. Градиент в дизайне нашего приложения лучше вообще не использовать.

7) Поэксперементируй с шрифтом, размером и цветом названия приложения в левом верхнем углу. Нужно постараться сделать его более лаконичным.

8) Количество выполненных задач расположено слишком близко к строке прогресса, пожалуйста подними их чуть выше. Либо можно разместить это количество сбоку от строки прогресса.

![Image](https://user-images.githubusercontent.com/107300467/230354767-38e60686-dc99-4653-9c32-5b78eb045929.png)

Возвращаю карточку обратно в колонку "Назначено".
Новый макет нужно предоставить до конца второго спринта. Результат прикрепить сюда же, в комментарии.

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/230708755-e49c3d05-dfca-4290-90e5-6c684f1e4c78.jpg)

**Comment by AlexValue** [comment]
Почти идеально!
Но у меня снова есть несколько предложений как можно улучшить:
1) Шрифт засечками для слова "Goally" не подходит к минималистичному стилю логтипа. Предлагаю вернуть шрифт из первого варианта макета. Либо поискать более современный шрифт.
<img width="163" alt="image" src="https://user-images.githubusercontent.com/107300467/230715008-489b866e-8b85-4c28-a28e-98843b8ee0bd.png">

2) Размер слова "Goally" нарушает гармонию и слишком притягивает внимание. Предлагаю вернуть размер и расположение текста как было в первом варианте макета.

3) Оттенок слова "Goally" выглядит слишком ядовитым. Предлагаю взять оттенок потемнее, либо понизить насыщенность.

4) Предлагаю изменить цвет дедлайнов на оранжевый, чтобы сохранить цветовую палитру оранжевый-зелёный

5) Предлагаю изменить цвет строки прогресса на зелёный потому что это разнообразит палитру интерфейса, которая сейчас в основном оранжевая. Кроме того, зелёный чаще ассоциируется с чем-то положительным, чем оранжевый.

6) Прошу на всякий случай проверить все оранжевые элементы, чтобы у них был одинаковый оттенок.

7) Линии в иконках стоит сделать потолще, при этом саму иконку можно чуть уменьшить, чтобы итоговый размер не изменился. 
<img width="396" alt="image" src="https://user-images.githubusercontent.com/107300467/230715666-9be6a9f4-2138-4442-81e6-877ea9c8c452.png">

8) Также прошу проверить, чтобы у всех иконок была одинаковая толщина линий. Сейчас у первой иконки линии толще. Если задумка была в том, чтобы у выбранной иконки линии становились толще, то можно оставить эту задумку, но при публикации макетов стоит прописывать такие моменты текстом, т.к. по одной картинке такое трудно понять.

Возвращаю карточку обратно в колонку "Назначено".
Новый макет нужно предоставить до конца текущего спринта (второго спринта).

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/230893378-3c0e09ac-a44c-4f81-8e46-72ab1f0b4e1a.jpg)

**Comment by AlexValue** [comment]
Осталось сделать 3 правки и можно закончить работу над этим заданием:

1) Первая иконка в меню снизу стала больше всех остальных. Её стоит уменьшить. Также можно упростить детали, скоратив количество горизонтальных полосок в этой иконке с 5 до 3

2) Стоит скруглить углы у третьей иконки в меню (звезда). Это сделает её современнее.

3) Картинку в цели лучше заменить на какую-нибудь конкоетную картинку. Например на фотографию продуктов. Углы у картинки должны быт скруглены как у бокса цели

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/230967326-1b361859-4740-411a-9c11-8beb4a851adb.jpg)

**Comment by AlexValue** [comment]
Принято
