### ISSUE TITLE
Вставить первый вариант иконки приложения, вписать название приложения

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#5]
1. Настроить отображение иконки приложения (файл с иконкой прикреплён ниже)
2. Настроить отображение названия приложения "Goally"

В результате нужно прикрепить в комментариях к этой карточке скриншот, где на рабочем столе смартфона отображается иконка нашего приложения и название.

![Image](https://user-images.githubusercontent.com/107300467/230035341-c3492db4-aadf-42d9-8cb2-426cd796349b.png)

**Comment by Waranim** [comment]
![Image](https://user-images.githubusercontent.com/129619485/230124071-0eb5bd5e-66fa-4f6a-8362-0dc87524530a.png)
