### ISSUE TITLE
Посмотреть лекцию по Git

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#7]
Посмотреть лекцию по Git
https://urfume.sharepoint.com/:v:/s/msteams_c7e9e0/EYa9ArLrzvhLlw_5rJ7CFSwBWH-fJWl5h-j_WRZ93OMhEw?e=cZ8xEi

После просмотра нужно написать в комментарии под этой карточкой "Задание выполнено"

**Comment by Waranim** [comment]
Задание выполнено

**Comment by Kaeto7** [comment]
Задание выполнено
