### ISSUE TITLE
Создать макет страницы "Создание цели"

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#8]
Описание страницы "Создание цели"
Это страница, содержащая поля для ввода данных пользователя, из этих данных (название цели, картинка, описание, дедлайн) формируется цель пользователя.
Эта страница вызывается после нажатия на кнопку "+" на главной странице.
Цель страницы - получение данных от пользователя для формирования его цели

Что должен показывать прототип:
UX - Расположение элементов с целью удобного использования всех функций пользователем
UI - Визуальное вополощение элементов с целю повышения эстетической привлекательности страницы
Какие инструменты можно использовать для создания макета
Любой растровый редактор, например, Adobe XD
Любой векторный редактор, например, Figma
Среду разработки Android Studio

На что ориентироваться:
Общие требования к проекту (см. документ "техническое задание" в чате)
Личная папка с референсами
Приложения конкурентов: "UP", "TickTick", "Цели и достижения"

Какие элементы должны быть на макете страницы

- Бокс (box) для отображения картинки цели. Это будет элемент отображения картинки, на который можно нажать как на кнопку. При нажатии на него пользователь будет выбирать на своём телефоне картинку и она будет вставляться в этот бокс. Пока пользователь ещё не выбрал картинку в боксе должна отображаться картинка по умолчанию, которая показывает отсутствие изображения. На макете этот бокс должен быть с картинкой по умолчанию.
- Бокс (box) для ввода названия цели. Это будет поле, в которое пользователь вводит краткую формулировку своей цели. Если поле ещё не заполнено, в нём должен отображаться блёклый текст "Чего вы хотите достичь?"
- Бокс (box) для ввода описания цели. Это будет поле, в которое пользователь вводит подробное описание своей цели. Если поле ещё не заполнено, в нём должен онображаться блёклый текст "Описание цели". Это поле должно быть большего размера по вертикальной оси, чем поле ввода названия цели.
- Бокс (box) для выбора дедлайна. Это будет поле для выбора дедлайна. Если дата ещё не выбрана, то в нём должен отображаться блёклый текст "Дедлайн"
- Бокс (box) для выбора приоритета. Это будет выпадающий список, в котором пользователь сможет выбрать приоритет для цели. Если категория ещё не выбрана, то в боксе должен отображаться блёклый текст "Приоритет". Также , внутри бокса с правого края должен отображаться треугольник, вершиной вниз, который будет обозначать выпадающий список.
- Бокс (box) для выбора категории. Это будет выпадающий список, в котором пользователь сможет выбрать категорию для цели. Если категория ещё не выбрана, то в боксе должен отображаться блёклый текст "Категория". Также , внутри бокса с правого края должен отображаться треугольник, вершиной вниз, который будет обозначать выпадающий список.
- Кнопка "добавить задачу"
- В самом низу должно быть 2 кнопки: "Отмена" и "Сохранить"

Что должно быть в результате
Макет страницы "Главная" в виде PNG картинки разрешением 1080 х 2340 пикселей
На изображении должен быть только макет интерфейса, без лишних рамок по краям.
Результат нужно прикрепитьв комментариях к этой карточке

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/230893709-de636479-90b9-4612-8742-588b88101980.jpg)

**Comment by AlexValue** [comment]
Хорошо
Но у меня есть одно замечание
- Ниже поля "Категория" нужно было создать кнопку "Добавить задачу". На данном макете её нет.

Предложения по улучшению:
1) Нужно убрать кнопку меню в правом верхнем углу. На этой странице её быть не должно.

2) Надпись сверху страницы "Создать" стоит переименовать в "Создание цели". Эта надпись должна быть выравнена посередине.

3) Стоит сделать скругление кнопок как у кнопки на главном экране. Также у кнопок стоит убрать тени. Шрифт кнопок должен соответсвовать шрифту у кнопок  на главном экране.
![Image](https://user-images.githubusercontent.com/107300467/230912915-72413a89-4b8c-4ccf-92a6-39ba495678e7.png)

4) У бокса с выбором картинки стоит сделать фон чуть светлее. Также, внутри бокса, под иконкой отсутствия картинки нужно разместить надпись "Выберете картинку"

5) У всех боксов стоит убрать рамки у величить скругление. Пример прикрепил ниже.
![Image](https://user-images.githubusercontent.com/107300467/230914833-972b813f-c8d8-41ed-ab37-98365001e654.png)

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/230971556-791fc310-4fbb-4179-aeee-82f8df79d099.jpg)

**Comment by AlexValue** [comment]
1) Текст "Выберете картинку" стоит сделать такого же размера, как текст в других полях.

2) Кнопка "добавить задачу" должна быть такого же размера как и поля. Можно подвинуть все боксы вверх, ближе к надписи "создание цели", чтобы было больше места для кнопки. Если места всё равно не хватит, то можно уменьшить поле с выбором картинки.

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/231186768-83e6531e-9a56-4660-81ec-58105a540ca1.jpg)

**Comment by AlexValue** [comment]
В целом, всё отлично!
Но стоит опустить текст "Выберете картинку" пониже.

**Comment by AniaKoriakina** [comment]
![Image](https://user-images.githubusercontent.com/82394052/231198879-6fda8c63-62c7-4111-8943-39e36ea622cd.jpg)

**Comment by AlexValue** [comment]
Принято
