### ISSUE TITLE
Пройти Unit 6: Data persistence из курса

### ISSUE THREAD

**Issue by AlexValue** [AlexValue/Goally#9]
Нужно изучить Unit 6 на тему "Сохранение данных в приложении" из курса "Android Basics with Compose" с сайта developer.android.com

Ссылка на стриницу курса со всеми юнитами
https://developer.android.com/courses/android-basics-compose/course

В результате, нужно написать в комментариях к этой карточке "Задание выполнено" после того, как вы пройдёте юнит.

**Comment by Waranim** [comment]
Задание выполнено
